// src/components/Footer.tsx
import React from 'react';
import { Heart, Instagram, Twitter, Mail, MapPin } from 'lucide-react';

export function Footer() {
  const footerLinks = {
    'Layanan': [
      'Kesehatan Mental',
      'Kesehatan Reproduksi',
      'Kesehatan Ibu & Anak',
      'Konsultasi Online'
    ],
    'Komunitas': [
      'Support Groups',
      'Event & Workshop',
      'Volunteer Program',
      'Artikel & Resources'
    ],
    'Tentang': [
      'Tentang Partner SEHATin',
      'Tim Kami',
      'Mitra & Partner',
      'Karir'
    ]
  };

  return (
    <footer className="bg-slate-900 text-white">
      <div className="max-w-7xl mx-auto px-6 lg:px-8 py-16">
        {/* Main Footer Content */}
        <div className="grid md:grid-cols-2 lg:grid-cols-5 gap-12 mb-12">
          {/* Brand */}
          <div className="lg:col-span-2 space-y-6">
            <div className="flex items-center gap-2">
              <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center">
                <Heart className="w-6 h-6" />
              </div>
              <span className="text-2xl">Partner SEHATin</span>
            </div>
            <p className="text-slate-400 leading-relaxed max-w-md">
              Ruang aman untuk Gen Z dalam membahas kesehatan mental, reproduksi, 
              serta kesehatan ibu dan anak. Karena kesehatanmu adalah prioritas kami.
            </p>
            
            {/* Social Media */}
            <div className="flex gap-4">
              <a 
                href="#" 
                className="w-10 h-10 bg-slate-800 hover:bg-blue-600 rounded-full flex items-center justify-center transition-colors"
                aria-label="Instagram"
              >
                <Instagram className="w-5 h-5" />
              </a>
              <a 
                href="#" 
                className="w-10 h-10 bg-slate-800 hover:bg-blue-600 rounded-full flex items-center justify-center transition-colors"
                aria-label="Twitter"
              >
                <Twitter className="w-5 h-5" />
              </a>
              <a 
                href="#" 
                className="w-10 h-10 bg-slate-800 hover:bg-blue-600 rounded-full flex items-center justify-center transition-colors"
                aria-label="Email"
              >
                <Mail className="w-5 h-5" />
              </a>
            </div>
          </div>

          {/* Links */}
          {Object.entries(footerLinks).map(([category, links]) => (
            <div key={category}>
              <h3 className="text-lg mb-4">{category}</h3>
              <ul className="space-y-3">
                {links.map((link) => (
                  <li key={link}>
                    <a 
                      href="#" 
                      className="text-slate-400 hover:text-white transition-colors"
                    >
                      {link}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Contact Info */}
        <div className="border-t border-slate-800 pt-8 mb-8">
          <div className="grid md:grid-cols-2 gap-6">
            <div className="flex items-start gap-3">
              <Mail className="w-5 h-5 text-blue-400 mt-1 flex-shrink-0" />
              <div>
                <p className="text-slate-300 mb-1">Email Kami</p>
                <a href="mailto:hello@partnersehatin.id" className="text-slate-400 hover:text-blue-400 transition-colors">
                  hello@partnersehatin.id
                </a>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <MapPin className="w-5 h-5 text-blue-400 mt-1 flex-shrink-0" />
              <div>
                <p className="text-slate-300 mb-1">Lokasi</p>
                <p className="text-slate-400">
                  Surabaya, Indonesia
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-slate-400 text-sm">
            © 2024 Partner SEHATin. All rights reserved.
          </p>
          <div className="flex gap-6 text-sm">
            <a href="#" className="text-slate-400 hover:text-white transition-colors">
              Privacy Policy
            </a>
            <a href="#" className="text-slate-400 hover:text-white transition-colors">
              Terms of Service
            </a>
            <a href="#" className="text-slate-400 hover:text-white transition-colors">
              Disclaimer
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}

// components/Layout/Footer.vue
<template>
  <footer class="bg-primary text-white">
    <div class="container mx-auto px-4 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <div class="col-span-1">
          <h3 class="text-2xl font-bold mb-4">PartnerSEHATin</h3>
          <p class="text-gray-300 text-sm">
            Platform kesehatan yang empatik dan inklusif untuk mendukung perjalanan kesehatanmu.
          </p>
          <div class="flex space-x-4 mt-6">
            <a href="#" class="text-gray-300 hover:text-white transition">Instagram</a>
            <a href="#" class="text-gray-300 hover:text-white transition">Facebook</a>
            <a href="#" class="text-gray-300 hover:text-white transition">Twitter</a>
            <a href="#" class="text-gray-300 hover:text-white transition">LinkedIn</a>
          </div>
        </div>
        
        <div>
          <h4 class="font-semibold mb-4">Layanan</h4>
          <ul class="space-y-2 text-gray-300 text-sm">
            <li><a href="#" class="hover:text-white transition">Kesehatan Mental</a></li>
            <li><a href="#" class="hover:text-white transition">Kesehatan Reproduksi</a></li>
            <li><a href="#" class="hover:text-white transition">Kesehatan Ibu & Anak</a></li>
            <li><a href="#" class="hover:text-white transition">Konsultasi Online</a></li>
          </ul>
        </div>
        
        <div>
          <h4 class="font-semibold mb-4">Komunitas</h4>
          <ul class="space-y-2 text-gray-300 text-sm">
            <li><a href="#" class="hover:text-white transition">Support Groups</a></li>
            <li><a href="#" class="hover:text-white transition">Peer Support</a></li>
            <li><a href="#" class="hover:text-white transition">Events & Workshops</a></li>
          </ul>
        </div>
        
        <div>
          <h4 class="font-semibold mb-4">Tentang</h4>
          <ul class="space-y-2 text-gray-300 text-sm">
            <li><a href="#" class="hover:text-white transition">Tentang Kami</a></li>
            <li><a href="#" class="hover:text-white transition">Misi & Visi</a></li>
            <li><a href="#" class="hover:text-white transition">Kontak</a></li>
          </ul>
        </div>
      </div>
      
      <div class="border-t border-blue-800 mt-8 pt-8 flex flex-col md:flex-row justify-between items-center">
        <p class="text-gray-300 text-sm">© 2023 PartnerSEHATin</p>
        <div class="flex space-x-6 mt-4 md:mt-0">
          <a href="#" class="text-gray-300 hover:text-white text-sm transition">Privacy Policy</a>
          <a href="#" class="text-gray-300 hover:text-white text-sm transition">Terms & Conditions</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
</script>
